### ISSUE TITLE
After running the UTXO -reindex needed

### ISSUE THREAD

**Issue by MCM-Mike** [in3rsha/bitcoin-utxo-dump#10]
I tried it twice with two of my nodes after running your UTXO tool I had to -reindex my nodes. 
Is this normal?

**Comment by beiex** [comment]
Did you turn off your node b4 attempting this? Otherwise it could have these sideeffects

**Comment by MCM-Mike** [comment]
Yes I did stop the bitcoind daemon prior to the start of your script. 

The dump did work "sort of" because I found some mined blocks which did not show up in the UTXO dump.

**Comment by beiex** [comment]
Not my script, in3rsha’s..
I didn’t have the problem, I would suggest shutting down btc, copying the chainstate somewhere and running it against that..
Maybe that solves the problem?!

What blocks did you find?
btw. if the blocks didn’t have any more unspent btc they are not supposed to show up

**Comment by MCM-Mike** [comment]
Ok, let me try this again. 

When dumping I did not found the following address 1GZTodCGRSUhp5SKAKFpnyvk6GT3iTwrKB in the dump.

**Comment by MCM-Mike** [comment]
Just for my understanding do I have to move the chainstate away or can is it supposed to be in the same folder as the bitcoind data? 
Could you verify my address problem ?

**Comment by in3rsha** [comment]
> Just for my understanding do I have to move the chainstate away or can is it supposed to be in the same folder as the bitcoind data?
> Could you verify my address problem ?

I coded this tool so that you can run it against your actual bitcoin chainstate database without corrupting it or having to move it to a different location.

The LevelDB database really doesn't like being accessed by different programs at the same time, which is why this tool should prompt you to run `bitcoin-cli stop` to shut down if it is already running. This should help prevent accidentally corrupting the database.

What **may be happening** is that you have set up bitcoin to auto-restart with a systemd service or something like that. Is that the case? If so, `bitcoind` may be starting in the background whilst this script is running, which means that two programs are accessing the chainstate database at the same time, causing a problem with it.

I just tested this script and I didn't have to `--reindex` when restarting Bitcoin. Do you have a systemd service running that auto-restarts Bitcoin?

**Comment by MCM-Mike** [comment]
Yes bitcoind is controlled by systemd but I stopped in manually to run your script and made sure it stays off during the dump. 

I am not having the problem anymore after last --reindex.
We can close this issue now.   

But if you would be so kind and double check why the above mentioned address is not shown in the UTXO dump is curious to me.

**Comment by in3rsha** [comment]
> Ok, let me try this again.
> 
> When dumping I did not find the following address 1GZTodCGRSUhp5SKAKFpnyvk6GT3iTwrKB in the dump.

There technically isn't an output at the address `1GZTodCGRSUhp5SKAKFpnyvk6GT3iTwrKB`. This is the output you are looking for:

https://learnmeabitcoin.com/explorer/transaction/924e17306773daa64835a49838cee85e85ed547031b6c8356f540d2b25dfaab7/output/0#scriptPubKey

You will notice that it has a P2PK lock on it that is locked to the public key `041951d706aeb3760975e0ceac5a667e04814ff98f29ee87d3b962cb262bab2893cae29773a373bcfe848ec5a384d52d88dbc40c6468ff2d71574593091fe091ad OP_CHECKSIG`. If you converted this public key to base58 address format you would get `1GZTodCGRSUhp5SKAKFpnyvk6GT3iTwrKB`.

However, an address refers to the use of a P2PKH locking script, which would mean you have hash160'd the above public key and place it in to a lock of the format `OP_DUP OP_HASH160 <hash160pubkey> OP_EQUALVERIFY OP_CHECKSIG`. However, the above public key has never been used in this type of lock, which is why the address is not showing up in the results (because it has technically not been used yet).

If you run the tool and ask for the complete script (and not just the addresses) with:

```
bitcoin-utxo-dump -f  count,txid,vout,type,script,address
```

You will find the UTXO you are looking for at this TXID:

```
cat utxodump.csv | rg "924e17306773daa64835a49838cee85e85ed547031b6c8356f540d2b25dfaab7"
45888463,924e17306773daa64835a49838cee85e85ed547031b6c8356f540d2b25dfaab7,0,p2pk,051951d706aeb3760975e0ceac5a667e04814ff98f29ee87d3b962cb262bab2893,
```

To save space, the public key you are searching for has been stored in _compressed format_ in the UTXO database, although in the blockchain you will find it in its uncompressed format.

```
uncompressed: 041951d706aeb3760975e0ceac5a667e04814ff98f29ee87d3b962cb262bab2893cae29773a373bcfe848e
compressed:  051951d706aeb3760975e0ceac5a667e04814ff98f29ee87d3b962cb262bab2893
```

Does that make sense?

**Comment by MCM-Mike** [comment]
Thank you for the detailed explanation. 
Yes it does make sense now. 

I was just curious because some of the dumps I was using from other sites like https://blockchair.com/dumps had the address in their total address list. 

Would it make sense for your script to include these addresses as well (feature) to have a full overview over the btc address space and the values?

**Comment by in3rsha** [comment]
Possibly, but at the moment I think it would misleading.

All of the UTXOs are accounted for, and all addresses are given for locking scripts that actually have them. A P2PK script does not have an address, and I don't think it would be a good idea to suggest that it does.

It would be better to understand that these outputs contain public keys that can be searched for, but not addresses. I'm reluctant to add a feature due to the fact that other tools are showing addresses where there technically aren't any.

I appreciate the suggestion, but at this moment in time I would prefer for the tool to be technically accurate.

**Comment by MCM-Mike** [comment]
Thank you very much for your help! :)
