### ISSUE TITLE
Are P2PK "scripts" compressed PKs? Why are there some PKs starting with 05?

### ISSUE THREAD

**Issue by streamofstars** [in3rsha/bitcoin-utxo-dump#27]
The usage section of the project description reads:

> script - The locking script placed on the output (this is just the hash160 public key or hash160 script for a P2PK, P2PKH, or P2SH)

Shouldn't it actually be "this is just the compressed public key for P2PK or hash160 script for a P2PKH and P2SH"? Also for P2WPKH it looks like hash160 prepended with 0014. I have not investigated other types.

I noticed the above when checking out some P2PK transactions in mempool. Can someone explain to me, assuming I'm right about the script output above, why some P2PK have script prefix different than 02 and 03? There are multiple ones with 04 and 05. 04 would be OK if the "script" was just uncompressed public key, but the key length suggests compressed public key and if so, the prefix should be 02 or 03 depending on the parity of Y coordinate, not 04 nor 05.

Example
```
bitcoin-utxo-dump -db <chainstatepath> -p2pkaddresses -f type,script,address,txid
grep 1Lx9PbLowBtAzMWttPuXhMA5dJzJsvaXMh utxodump.csv
p2pk,05ffffcdeee179409d5b0e3133929d6c1292d57768182e650878304dc6867e7a0b,1Lx9PbLowBtAzMWttPuXhMA5dJzJsvaXMh,d1aa3ca0641ccbd624097847c227448823f0b5d6eb8c0b047335c056886f9084
```

By the way, why it also returns p2pkh utxo with identical address?
`p2pkh,dad84560c59d0cfe43572a7dbf57bfea7a004280,1Lx9PbLowBtAzMWttPuXhMA5dJzJsvaXMh,8309ae00b956bff6e1acf247bdae5d9b7b3ea44c382a32fdb66bb1dd3fa806df`

Am I missing something?

**Comment by in3rsha** [comment]
> Shouldn't it actually be "this is just the compressed public key for P2PK or hash160 script for a P2PKH and P2SH"?

Yes that's about right. I've updated the README to provide more information about the script field. It was pretty vague. Thanks for pointing that out. 

To summarize what you're seeing in the `script` field:

* **P2PKH** = The hash160 of a compressed public key.
* **P2PK** = A compressed public key (even if the original script contained an uncompressed public key). A compressed public key always starts with a `02` or `03` to indicate whether the `y` value is even or odd. However, if the original script contained an uncompressed public key, it gets compressed when storing it in the chainstate database to save space. We then use an `04` or `05` to indicate that it was originally an uncompressed key and to also indicate whether the original `y` was even or odd.
* **P2SH** = The hash160 of a script.
* **Everything else** = The full scriptpubkey.

> Also for P2WPKH it looks like hash160 prepended with 0014. I have not investigated other types.

Yes that's correct. For anything that isn't a P2PK, P2PKH, or P2SH, you get the full scriptpubkey.

* **P2WPKH** = Always starts with a `0014`, followed by the hash160 of a public key.
* **P2WSH** = Always starts with a `0020`, followed by the sha256 hash of a script.

See [BIP 141: Segregated Witness](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki)

> Can someone explain to me, assuming I'm right about the script output above, why some P2PK have script prefix different than 02 and 03? There are multiple ones with 04 and 05. 04 would be OK if the "script" was just uncompressed public key, but the key length suggests compressed public key and if so, the prefix should be 02 or 03 depending on the parity of Y coordinate, not 04 nor 05.

You've pretty much got it. The `04` and `05` indicates the parity of the `y` co-ordinate, but also that the original P2PK contained an _uncompressed_ public key. Compressing it for the chainstate database saves space.

```
00  = P2PKH <- upcoming data is the hash160 public key
01  = P2SH  <- upcoming data is the hash160 of a script
02  = P2PK  <- upcoming data is a compressed public key (nsize makes up part of the public key) [y=even]
03  = P2PK  <- upcoming data is a compressed public key (nsize makes up part of the public key) [y=odd]
04  = P2PK  <- upcoming data is an uncompressed public key (but has been compressed for leveldb) [y=even]
05  = P2PK  <- upcoming data is an uncompressed public key (but has been compressed for leveldb) [y=odd]
06+ =       <- indicates size of upcoming full script (subtract 6 to get the actual size in bytes)
```

See this [bitcoin chainstate parser](https://github.com/in3rsha/bitcoin-chainstate-parser#3-third-varint).

> By the way, why it also returns p2pkh utxo with identical address?

You're using the `-p2pkaddresses` flag, which takes the public key from the P2PK script and shows the address it would have if it was being used in a P2PKH script.

P2PK scripts do not have addresses though, which is why they are not shown by this script default.

Some people asked for this feature because some block explorers show an "address" for P2PK scripts, and I believe they wanted to be able to identify unspent outputs using these addresses as identifiers.
