### ISSUE TITLE
Identify spent UTXO 

### ISSUE THREAD

**Issue by seccobit** [in3rsha/bitcoin-utxo-dump#6]
Hi, 

is there a way to identify UTXO that have been spent, and total amount spent for each UTXO?
Sorry, not really an issue, but couldn't find any other forum where I could raise this.

**Comment by in3rsha** [comment]
No problem!

UTXO stands for "Unspent Transaction Output". These are most interesting in Bitcoin because they need to be accessed quickly when validating new transactions. This is why UTXOs are given their own special database outside the blockchain, which is what this tool accesses.

Therefore, if you want to access the _spent_ outputs you just need to look inside the blockchain, which contains every transaction and the outputs created from them. The vast majority of outputs in the blockchain are going to be spent, as the UTXOs only make up a small percentage of the outputs that haven't been spent yet.

So to get the spent outputs (which there are going to be lots of, probably billions), you need to iterate through the data inside the blockchain. The best tool I've found for doing this is: `[bitooin-iterate](https://github.com/rustyrussell/bitcoin-iterate)`

That tool should allow you to get every single output (including it's value) from the blockchain. If you just want to get the _spent_ ones, you may need to get the unspent outputs (UTXOs) also then subtract those from the full list of outputs.

Hope that helps.

**Comment by seccobit** [comment]
Thanks! and thanks for bitcoin-utxo-dump (very useful). bitcoin-iterate should work, going to try now. I would need to include timestamp (creation) and timestamp (destruction) it seems as it can be added to the output (https://github.com/rustyrussell/bitcoin-iterate/blob/master/doc/bitcoin-iterate.1.txt ). Basically, I am trying to determine the avg. lifespan of a UTXO (spent on its entirety), the issue here is that each time a portion of UTXO is spent, new UTXOs are created (so single UTXO time span is not really a good metrics)... any suggestion is welcomed.

**Comment by in3rsha** [comment]
No problem.

Well, strictly speaking it's not possible to spend a _portion_ of a UTXO. When you spend a UTXO in a transaction, you are always using it all up to create new outputs from it. Some of those could be used as change and sent back to the same address, but this doesn't always happen (change could be sent to a new address entirely), so it would be very difficult to try and determine if only a "portion" of a UTXO is spent in a transaction.

I would say that the destruction of a UTXO is when it is used as an input in a transaction (when it gets spent). Trying to work out the end time of a UTXO would be very difficult otherwise.

Just thought I'd share my thoughts on that one in case that helps.

**Comment by seccobit** [comment]
Hey in3rsha, 
thanks for the above, 
one more, Do you know by any chance why when I run the below: 

$ ./bitcoin-iterate </home/mypath/blocks> -q --tx=%bh,%tl 

or any other valid commands from bitcoin-iterate I always get this back: 

""
Usage: ./bitcoin-iterate 
Valid block, transaction, input, output, and utxo format:
  <literal>: unquoted
  %bl: block length
  %bv: block version
  %bp: block prev hash
  %bm: block merkle hash
  %bs: block timestamp
  %bt: block target
  %bn: block nonce
...... 
""
I must miss something.   
Maybe important to note that on this machine have not yet finished to download Bitcoin blockchain (currently on Block height=482717). I wouldn't expect this to matter but I thought to mention it anyway...just in case it does.

**Comment by in3rsha** [comment]
Closing this issue for now.
